"""
DOPPEL Shared Constants and Error Codes
"""
from enum import Enum

class ErrorCode(str, Enum):
    # Auth Errors
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED"
    AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
    AUTH_USER_EXISTS = "AUTH_USER_EXISTS"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_ACCOUNT_SUSPENDED = "AUTH_ACCOUNT_SUSPENDED"

    # Consent Errors
    CONSENT_BIOMETRIC_REQUIRED = "CONSENT_BIOMETRIC_REQUIRED"
    CONSENT_DISCOVERY_REQUIRED = "CONSENT_DISCOVERY_REQUIRED"
    CONSENT_REVOKED = "CONSENT_REVOKED"

    # Face AI & Quality Errors
    FACE_NOT_DETECTED = "FACE_NOT_DETECTED"
    MULTIPLE_FACES_DETECTED = "MULTIPLE_FACES_DETECTED"
    IMAGE_TOO_BLURRY = "IMAGE_TOO_BLURRY"
    IMAGE_TOO_DARK = "IMAGE_TOO_DARK"
    IMAGE_TOO_BRIGHT = "IMAGE_TOO_BRIGHT"
    IMAGE_POOR_CONTRAST = "IMAGE_POOR_CONTRAST"
    FACE_TOO_SMALL = "FACE_TOO_SMALL"
    FACE_EXTREME_POSE = "FACE_EXTREME_POSE"
    INVALID_IMAGE_FORMAT = "INVALID_IMAGE_FORMAT"
    IMAGE_FILE_TOO_LARGE = "IMAGE_FILE_TOO_LARGE"

    # Matching & Discovery Errors
    PROFILE_NOT_ENROLLED = "PROFILE_NOT_ENROLLED"
    DISCOVERY_DISABLED = "DISCOVERY_DISABLED"
    MATCHING_FAILED = "MATCHING_FAILED"
    USER_BLOCKED = "USER_BLOCKED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    # Generic & System
    VALIDATION_ERROR = "VALIDATION_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    NOT_FOUND = "NOT_FOUND"
    FORBIDDEN = "FORBIDDEN"


class AccountStatus(str, Enum):
    ACTIVE = "active"
    SUSPENDED = "suspended"
    PENDING_VERIFICATION = "pending_verification"
    DELETED = "deleted"


class ProfileVisibility(str, Enum):
    PUBLIC = "public"
    DISCOVERY_ONLY = "discovery_only"
    PRIVATE = "private"


class ConnectionStatus(str, Enum):
    PENDING = "pending"
    ACCEPTED = "accepted"
    REJECTED = "rejected"
    BLOCKED = "blocked"
